### ISSUE TITLE
Loading... Layers Remaining: 1

### ISSUE THREAD

**Issue by owainsky** [bedrock-viz/bedrock-viz#21]
I've set up MCPE Viz 0.1.1 to generate map files which are output to a directory serviced by IIS. When I use the map, everything seems to work other than when I try to use the functions that show mobs or objects. At that point, the message "Loading... Layers Remaining: 1" stays on screen and never goes away while the data doesn't appear either; this is the case even if I load the map locally via the file system. If I flip "loadGeoJSONFlag" to false in the map's associated JS file, the IIS hosted version starts giving me a Vector Load Error but the local file-based one now shows the associated details correctly.

**Comment by tomnolan** [comment]
Did you make sure to add .geojson to the mime types in IIS? You should add it to the server node in IIS since adding it to the website in IIS will add a web.config that you will then need to keep track of (if you overwrite that file the mime type will go away). Just use application/json
![iis geojson config](https://user-images.githubusercontent.com/7898473/76725121-9f28f800-6723-11ea-9e5f-e5f89980f71f.png)

**Comment by owainsky** [comment]
Argh. Rookie mistake and you are quite right. Thanks!

**Comment by owainsky** [comment]
PBCAK.
