### ISSUE TITLE
[Web App] Large map renders fail to load in browser

### ISSUE THREAD

**Issue by paulgrahek** [bedrock-viz/bedrock-viz#9]
Large map renders fail to load in Chromium and Firefox when the PNG file gets too big. In my case, the map dimensions were 22000x35000 pixels at 13.8 MB in size. 
OpenLayers supports tiling which would significantly improve Web App performance on bigger maps, but this likely requires a rewrite of the render generator as well.

**Comment by tomnolan** [comment]
@paulgrahek did you try using the tiles switch for this? If you build from the latest commit, you should be able to do something like this and have it work... I have a similar problem with one of my realms.

bedrock-viz.exe -db <db> -outdir <outdir> -tiles=2048,2048

You might be able to use --autotiles as well. That one creates new tiles when the size is larger than 5000 wide or 5000 tall and it defaults to a width and height of 1024. Would be great to do some testing to see where the sweet spot is for tile size.

**Comment by counterfitninja** [comment]
Hey @tomnolan did you take a look at the fix in #23 where @bazfp fixed s memory leak? That version works well with large maps

**Comment by tomnolan** [comment]
Yea, we merged that fix in one of the last commits and it works amazingly well. This issue seems more related to openlayers/web browser choking on enormous images for huge worlds. 

I actually think we should have auto-tile enabled by default, with a higher default tile size, and change the cmdline option to be "--no-auto-tile" to keep large images if people really want them. Seems like a better way to handle the huge tiles that can get generated with big worlds.

**Comment by counterfitninja** [comment]
I agree. Titles would be better overall I think. Generates smaller files and makes the processing better for generation.
